# wrangler.toml
name = "octopus-energy-qrcode"
main = "src/worker.js"
compatibility_date = "2025-05-05" # Use a recent compatibility date

[assets]
directory = "./public/"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true